INSERT INTO CUSTOMER(EMAIL,USER_PASS,CUSTOMER_NAME) VALUES ('praveen@gmail.com','praveen123','Praveen');
INSERT INTO CUSTOMER(EMAIL,USER_PASS,CUSTOMER_NAME) VALUES ('kolli@gmail.com','kolli123','kolli');
INSERT INTO CUSTOMER(EMAIL,USER_PASS,CUSTOMER_NAME) VALUES ('Naga@gmail.com','Naga123','Naga');